### ISSUE TITLE
"Taiyaki keeps stopping"

### ISSUE THREAD

**Issue by zikdoz** [Michael24884/TaiYaKiAnime#12]
I've tried all of the given 3 apks, but neither of them works with this same error. Am I missing something? Maybe OS version is too low for this app?

My device is Xiaomi Mi Pad 4 with Android 8.1, arch is 64-bit ARMv8-A.

<details>
<summary>Full error text</summary>

```
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.taiyakianime. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:184)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.0:1)
	at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:78)
	at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:68)
	at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleIntent(FcmInstanceIdRefreshHandlerService.java:23)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```
</details>

UPD: same goes for OnePlus 7 Pro with Android 10 (OxygenOS 10.3.4), same arch.

**Comment by Michael24884** [comment]
Should work now, but please wait a bit more as in Android the headers need to be explicitly set

**Comment by zikdoz** [comment]
Okay, thanks! I'll try again tomorrow

**Comment by zikdoz** [comment]
Thanks! It works now
